sudo: false
matrix:
  include:
  - env: PLATFORM=ios
    os: osx
    osx_image: xcode10.2
    language: objective-c
  - env: PLATFORM=android
    os: linux
    dist: xenial
    language: android
    jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
  - sys-img-x86-android-$ANDROID_API_LEVEL
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_install:
- nvm install 8.16.0
- nvm use 8.16.0
- npm install -g cordova ionic
install:
- npm install
script:
- npm run ionic:build
- cordova plugin add cordova-plugin-bambuser@0.9.8
- ionic cordova platform add $PLATFORM
- npm run prepare:$PLATFORM
- ionic cordova build $PLATFORM
